---
title: "CodeBook.md"
author: "Owen Pauli"
date: "28/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#This is the code book for the project

##How to get to the tiny_data.txt:
1. Download data from the link below and unzip it into working directory of R Studio.
2. Run the R script.

## About the source data
The data linked to from the course website represent data collected from the accelerometers from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

Here are the data for the project:

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## About R script
The script run_analysis.R does the following five steps:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## About variables:   
* `features` contains the correct names for the `x_data` dataset.
* `x_train`, `y_train`, `x_test`, `y_test`, `subject_train` and `subject_test` read the tables of the same name from the project files.
* `x_data`, `y_data` and `subject_data` merge the previous datasets.